CREATE TABLE klient
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    imie         VARCHAR(255),
    nazwisko     VARCHAR(255),
    email        VARCHAR(255),
    ulica        VARCHAR(255),
    numer        VARCHAR(255),
    kod_pocztowy VARCHAR(255),
    miasto       VARCHAR(255),
    CONSTRAINT pk_klient PRIMARY KEY (id)
);

CREATE TABLE pracownik
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    imie           VARCHAR(255),
    nazwisko       VARCHAR(255),
    stanowisko     VARCHAR(255),
    numer_telefonu VARCHAR(255),
    email          VARCHAR(255),
    CONSTRAINT pk_pracownik PRIMARY KEY (id)
);

CREATE TABLE towar
(
    id               BIGINT NOT NULL,
    nazwa_produktu   VARCHAR(255),
    cena_jednostkowa DOUBLE PRECISION,
    jednostka_miara  VARCHAR(255),
    stan_magazynowy  DOUBLE PRECISION,
    opis             VARCHAR(255),
    CONSTRAINT pk_towar PRIMARY KEY (id)
);

CREATE TABLE zamowienie
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    klient_id         BIGINT                                  NOT NULL,
    pracownik_id      BIGINT                                  NOT NULL,
    status            VARCHAR(255),
    data_zalozenia    TIMESTAMP WITHOUT TIME ZONE,
    termin_realizacji TIMESTAMP WITHOUT TIME ZONE,
    cena_laczna       DOUBLE PRECISION,
    CONSTRAINT pk_zamowienie PRIMARY KEY (id)
);

CREATE TABLE zamowienie_towar
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    zamowienie_id  BIGINT                                  NOT NULL,
    towar_id       BIGINT                                  NOT NULL,
    ilosc          DOUBLE PRECISION,
    cena_sprzedazy DOUBLE PRECISION,
    CONSTRAINT pk_zamowienietowar PRIMARY KEY (id)
);

ALTER TABLE zamowienie_towar
    ADD CONSTRAINT FK_ZAMOWIENIETOWAR_ON_TOWAR FOREIGN KEY (towar_id) REFERENCES towar (id);

ALTER TABLE zamowienie_towar
    ADD CONSTRAINT FK_ZAMOWIENIETOWAR_ON_ZAMOWIENIE FOREIGN KEY (zamowienie_id) REFERENCES zamowienie (id);

ALTER TABLE zamowienie
    ADD CONSTRAINT FK_ZAMOWIENIE_ON_KLIENT FOREIGN KEY (klient_id) REFERENCES klient (id);

ALTER TABLE zamowienie
    ADD CONSTRAINT FK_ZAMOWIENIE_ON_PRACOWNIK FOREIGN KEY (pracownik_id) REFERENCES pracownik (id);