CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    email    VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE klient
    ADD user_id BIGINT;

ALTER TABLE klient
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE pracownik
    ADD user_id BIGINT;

ALTER TABLE pracownik
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE klient
    ADD CONSTRAINT uc_klient_user UNIQUE (user_id);

ALTER TABLE pracownik
    ADD CONSTRAINT uc_pracownik_user UNIQUE (user_id);

ALTER TABLE klient
    ADD CONSTRAINT FK_KLIENT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE pracownik
    ADD CONSTRAINT FK_PRACOWNIK_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);